# Generated by Django 5.1.2 on 2024-10-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takim',
            name='takim_tipi',
            field=models.CharField(max_length=50),
        ),
    ]
