# Generated by Django 5.1.2 on 2024-10-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0002_alter_takim_takim_tipi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucak',
            name='ad',
            field=models.CharField(max_length=50),
        ),
    ]
