# Generated by Django 5.1.2 on 2024-10-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0004_remove_parca_kullanilan_ucak_remove_personel_isim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='sifre',
            field=models.CharField(default='temporary_password', max_length=128),
        ),
        migrations.AlterField(
            model_name='personel',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
