# Generated by Django 5.1.2 on 2024-10-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0005_personel_sifre_alter_personel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='sifre',
            field=models.CharField(max_length=128),
        ),
    ]
