# Generated by Django 5.1.2 on 2024-10-21 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0006_alter_personel_sifre'),
    ]

    operations = [
        migrations.AddField(
            model_name='parca',
            name='kullanilan_ucak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kullanilan_parcalar', to='uretim.ucak'),
        ),
    ]
