# Generated by Django 5.1.2 on 2024-10-22 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0008_uretilenucak'),
    ]

    operations = [
        migrations.AddField(
            model_name='parca',
            name='ureten_personel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uretim.personel'),
        ),
    ]
