# Generated by Django 5.1.2 on 2024-10-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0009_parca_ureten_personel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parca',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='parca',
            name='stok_adedi',
        ),
    ]
