# Generated by Django 5.1.2 on 2024-10-22 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0010_alter_parca_unique_together_remove_parca_stok_adedi'),
    ]

    operations = [
        migrations.AddField(
            model_name='uretilenucak',
            name='ureten_personel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uretim.personel'),
        ),
        migrations.AlterField(
            model_name='uretilenucak',
            name='kullanilan_parcalar',
            field=models.ManyToManyField(to='uretim.parca'),
        ),
    ]
